export const forecastData = [
  {
    date: "Today",
    aqi: 47,
    pollutant: "PM2.5",
    concentration: 8.6,
    bgColor: "bg-green-300",
  },
  {
    date: "Tomorrow",
    aqi: 85,
    pollutant: "PM10",
    concentration: 16.2,
    bgColor: "bg-yellow-300",
  },
  {
    date: "Wed",
    aqi: 62,
    pollutant: "O3",
    concentration: 12.4,
    bgColor: "bg-green-300",
  },
  {
    date: "Tomorrow",
    aqi: 85,
    pollutant: "PM10",
    concentration: 16.2,
    bgColor: "bg-yellow-300",
  },
  {
    date: "Wed",
    aqi: 62,
    pollutant: "O3",
    concentration: 12.4,
    bgColor: "bg-green-300",
  },
  {
    date: "Thu",
    aqi: 95,
    pollutant: "NO2",
    concentration: 20.1,
    bgColor: "bg-red-500",
  },

  {
    date: "Tomorrow",
    aqi: 85,
    pollutant: "PM10",
    concentration: 16.2,
    bgColor: "bg-yellow-300",
  },
  {
    date: "Wed",
    aqi: 62,
    pollutant: "O3",
    concentration: 12.4,
    bgColor: "bg-green-300",
  },
  {
    date: "Thu",
    aqi: 95,
    pollutant: "NO2",
    concentration: 20.1,
    bgColor: "bg-red-500",
  },
];
